release:

builds:
- id: bb-pipeline
  main: ./cmd/pipeline/main.go
  binary: bb-pipeline
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  env:
  - CGO_ENABLED=0

archives:
- builds:
  - bb-pipeline
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
