release:

builds:
- id: bb-aws-connect
  main: main.go
  binary: bb-aws-connect
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  env:
  - CGO_ENABLED=0

archives:
- builds:
  - bb-aws-connect
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - license: MIT
    maintainer: Bitbull
    description: Bitbull CLI
    homepage: https://github.com/bitbull-team/bb-aws-connect/
    suggests:
      - awscli
      - session-manager-plugin
    formats:
      - rpm
      - deb
